### ISSUE TITLE
Allow passing in single files

### ISSUE THREAD

**Issue by TonioF** [multiply-org/atmospheric_correction#4]
The atmospheric correction expects some of its auxiliary data (as the MODIS MCD43 files) to be placed in a single folder that is to be browsed. It would be good if it were possible to hand in the files directly, especially when these might be located in different folders.

**Comment by MarcYin** [comment]
This is possible by creating VRT file for MCD43 on a daily basis covering the whole world (geographically not full dataset) and update the VRT file when new MCD43 is downloaded.

**Comment by TonioF** [comment]
So you'd propose passing a single .vrt-file which then is updated internally by the ac? This would still require the AC to download the files itself. What I think of is some way to hand in the single files. 
A collective file (like the .vrt) could be a solution to this, though.

**Comment by MarcYin** [comment]
Yes, if user only needs to do the ac without bothering other part, it should done in this way. 

If we have a better version of 'MCD43', better quality (optional), and saved in geotif format or any other file format supported by gdal virtual file system (important), we can simply pass only files, even url to remote files. Then there is no difference if we pass the file or let the AC download the file, as you can simply pass url to gdal and this is what I have done for other DEM data...

So I think the important thing is to have a better way to store/access the 'MCD43' or we can have our own version of 'MCD43', rather than to think about on which part we should download it.
